[package]
name = "csv-merger"
version = "0.1.1"
description = "A command line tool for merging multiple CSV files into one"
license = "MIT"
authors = ["park-dev <kirk.paradis@gmail.com>"]
edition = "2018"

[dependencies]
csv = "1.2.1"
